os: linux
dist: trusty
language: python

addons:
   apt:
      packages:
         - netcdf-bin libnetcdf-dev openmpi-bin libopenmpi-dev gfortran

install:
   - pip install pyyaml numpy xarray netcdf4 "cftime<1.1.2"
   - pip install -r docs/py_requirements.txt

python:
   - '2.7'
   - '3.6'

script:
   - cd docs/src; make html
   - cd ../../MARBL_tools; ./run_test_suite.sh

branches:
   only:
      - development
      - stable
      - cesm2.0
