language: python
sudo: required

addons:
   apt:
      sources:
         - ubuntu-toolchain-r-test
      packages:
         - netcdf-bin libnetcdf-dev openmpi-bin libopenmpi-dev gfortran-4.8

install:
   - sudo ln -s /usr/bin/gfortran-4.8 /usr/bin/gfortran
   - pip install pyyaml numpy xarray netcdf4
   - pip install -r docs/py_requirements.txt

python:
   - '2.7'
   - '3.6'

script:
   - cd docs/src; make html
   - cd ../../MARBL_tools; ./run_test_suite.sh

branches:
   only:
      - development
      - stable
      - cesm2.0
