language: python
sudo: required
before_install:
  - sudo apt-get install gfortran
install:
  - pip install pyyaml
  - pip install sphinx
  - pip install sphinx_rtd_theme==0.2.5b1
  - pip install sphinxcontrib-bibtex
python:
  - '2.7'
  - '3.6'
script:
  - cd docs/src; make html
  - cd ../../MARBL_tools; ./run_test_suite.sh

branches:
  only:
  - development
  - stable
  - cesm2.0